### ISSUE TITLE
krita does not draw with OpenGL canvas.

### ISSUE THREAD

**Issue by mesufesu** [danvd/wlroots-eglstreams#11]
krita 4.4.3
nvidia 460.67-4
wlroots g10c95e2b
sway 1d62d6bf

When using OpenGL accelerated canvas the window gets stuck after loading an image, i.e. when the canvas appears.

**Comment by danvd** [comment]
Unfortunately krita does not support native wayland, xwayland only as of now. What it means for us is that it uses software opengl rendering and is very slow.
Looking forward for nvidia 470 driver release that will eventually support accelerated xwayland

**Comment by mesufesu** [comment]
Indeed, you are correct. I had assumed for it to be native, but it forces xcb somehow.
