### ISSUE TITLE
Failed to create GLES2 renderer

### ISSUE THREAD

**Issue by mesufesu** [danvd/wlroots-eglstreams#12]
recent master doesn't run anymore.
- nvidia 465.24.02-4

> 00:00:00.002 [ERROR] [sway/main.c:97] !!! Proprietary Nvidia drivers are in use !!!
> 00:00:00.370 [ERROR] [wlr] [render/gles2/renderer.c:810] EGL_EXT_image_dma_buf_import not supported
> 00:00:00.370 [ERROR] [wlr] [render/gles2/renderer.c:769] Failed to create GLES2 renderer
> 00:00:00.375 [ERROR] [wlr] [backend/headless/backend.c:259] Failed to get DRM device FD from renderer
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:737] connector DP-1: Failed to initialize renderer:initial page-flip failed
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:807] connector DP-1: Failed to initialize renderer for plane
> 00:00:01.159 [ERROR] [sway/config/output.c:417] Failed to commit output DP-1
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:737] connector DP-2: Failed to initialize renderer:initial page-flip failed
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:807] connector DP-2: Failed to initialize renderer for plane
> 00:00:01.159 [ERROR] [sway/config/output.c:417] Failed to commit output DP-2
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:737] connector DP-1: Failed to initialize renderer:initial page-flip failed
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:807] connector DP-1: Failed to initialize renderer for plane
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [render/swapchain.c:111] Failed to allocate buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/renderer.c:129] Failed to acquire swapchain buffer
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:737] connector DP-2: Failed to initialize renderer:initial page-flip failed
> 00:00:01.159 [ERROR] [wlr] [backend/drm/drm.c:807] connector DP-2: Failed to initialize renderer for plane
> 00:00:16.335 [ERROR] [wlr] [backend/drm/drm.c:1547] drmHandleEvent failed

[Full log](https://gist.github.com/mesufesu/f90e52f21b187f6d1b9363b30cb666c5).

**Comment by danvd** [comment]
Thank you. wlroots has raised version and my sway got the previous version linked. That's why I missed the breakage.
Fixed now. Please check if it works.

**Comment by mesufesu** [comment]
Seems fine now, thanks.
