### ISSUE TITLE
VRR support

### ISSUE THREAD

**Issue by chaitan3** [danvd/wlroots-eglstreams#13]
Is there any plan to add VRR/Adaptive Sync support? I tested using "output * adaptive_sync on" in sway and it does not seem to work.

Plasma just added VRR support for EglStreams: 
https://invent.kde.org/plasma/kwin/-/merge_requests/718. 

It would be nice if this wlroots fork has it too.

**Comment by danvd** [comment]
Hi, I need to learn about the subject a little bit.

**Comment by danvd** [comment]
@chaitan3 "vrr_capable" is just a property of drm connector and it looks like nvidia blob does not even expose it (I used https://github.com/NickCis/drm_tool to check), so it won't work anyway. 
Maybe it supports only hardware vrr which my monitors lack.

Could you test what properties does your setup have?

**Comment by chaitan3** [comment]
I tested drm_tool and I do not see any vrr_capable or vrr_enabled strings in the connector output. 

We will have to wait for the Nvidia driver to expose these properties before having VRR :(

**Comment by danvd** [comment]
I'm closing this for now. If output of drm_tool will change sometime and the issue will persist, we can reopen it.
