### ISSUE TITLE
Alacritty: eglCreateWindowSurface failed

### ISSUE THREAD

**Issue by dbrgn** [danvd/wlroots-eglstreams#15]
On my laptop, I'm using sway + alacritty without issues using an Intel GPU.

However on my PC, with this fork, when starting alacritty I get the following error message:

```
[2021-05-02 02:38:56.600289150] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                        Error creating GL context; eglCreateWindowSurface failed
```

Any idea what the reason could be? Is there a way to further debug this?

**Comment by dbrgn** [comment]
Probably not the problem of wlroots-eglstreams as it affects others too (e.g. weston-eglstream).

- https://github.com/alacritty/alacritty/issues/1269
- https://github.com/rust-windowing/glutin/issues/1188

**Comment by danvd** [comment]
Hi, @dbrgn 
Yes, It's a bug of nvidia blob. There are probably some constraints on egl context. 
I also used alacritty before, but now switched to termite and happy with it.

**Comment by dbrgn** [comment]
Thanks @danvd. So far everything else wayland-native runs great. If you have an idea about #14 that would be highly appreciated, xwayland is barely usable.
