### ISSUE TITLE
Screen capture rotated by 180 degrees

### ISSUE THREAD

**Issue by chaitan3** [danvd/wlroots-eglstreams#16]
The screen capture in webrtc is rotated by 180 degrees when using xdg-desktop-portal-wlr
https://github.com/emersion/xdg-desktop-portal-wlr

Can be tested on the website below:
https://mozilla.github.io/webrtc-landing/gum_test.html

**Comment by danvd** [comment]
Hi, this depends on #9. In EGL Y coordinate is upside down compared to DRM. Need to tweak shaders+matrices to make it work right.

**Comment by danvd** [comment]
Hi @chaitan3, please recheck with latest changes. Should be fixed now.

**Comment by chaitan3** [comment]
Yes, it is fixed. Thanks a lot!
