### ISSUE TITLE
KwinFT incompatibility

### ISSUE THREAD

**Issue by XakepSDK** [danvd/wlroots-eglstreams#21]
While trying to build KwinFT with this fork instead of wlroots, user got an error.

I can help with KwinFT installation on Arch if you are interested. AUR pkgbuilds are bit wrong and pull half of plasma-git.

This is not my build log.
https://gist.github.com/XakepSDK/1bc6dc80617eecb3e99c791d07738d1a

**Comment by danvd** [comment]
Hi @XakepSDK,
I wonder which part of KwinFt uses wlroots? The attached build build log seems to have not so much common with wlroots source.

One more question: which original version of wlroots makes the build finish successfully? cloned from git or bundled in Arch package?

Anyway, may be I'm missing something. I also has Arch and can repeat steps that lead to error.

**Comment by XakepSDK** [comment]
> I wonder which part of KwinFt uses wlroots?

I don't know.

wlroots 0.14 is minimum requirement. I can build it with wlroots-git.

Here are my PKGBUILDs
Install in this order:
1. Wrapland
2. Disman
3. Kdisplay
4. KwinFT


[pkgbuilds.zip](https://github.com/danvd/wlroots-eglstreams/files/6720506/pkgbuilds.zip)

**Comment by danvd** [comment]
Ok, will do

**Comment by danvd** [comment]
@XakepSDK , could you please provide also your pkgbuilds for the following dependencies:
kdecoration-git
wlroots-git

**Comment by XakepSDK** [comment]
You can change wlroots-git to wlroots in deps in PKGBUILDs
wlroots 0.14 was required, it's in main repo now

I used this kdecoration:
https://aur.archlinux.org/packages/kdecoration-git

**Comment by kodatarule** [comment]
Heya, is there any update on this ?

**Comment by danvd** [comment]
Issue has been fixed recently.

To build latest kwinft form git I had to make some changes to its source (not related to wlroots-eglstreams)
[0001-wip-fix.patch.zip](https://github.com/danvd/wlroots-eglstreams/files/6967453/0001-wip-fix.patch.zip)

**Comment by kodatarule** [comment]
Yeah the build worked, but it rendered a black screen sadly

**Comment by Tank-Missile** [comment]
Same problem here. I built kwinft-git with wlroots-eglstreams-git and all I get is a black screen before being booted back to the login screen.

**Comment by danvd** [comment]
Will try to check it too. I just need to install kde and replace kwin with kwinft, right?

**Comment by Tank-Missile** [comment]
@danvd Not exactly. You will need to install kdecoration-git first or kwinft-git will not compile. Also make sure wlroots-eglstreams-git is installed instead of wlroots-git before compiling.

**Comment by danvd** [comment]
I tried kwinft and also got black screen. This is because at some point of time it tries to call getPlatformDisplay explicitly asking for a MESA platform (we're using external platform for eglstreams), and, after getting  falls back to software rendering and fails again eventually. I guess nothing can fix it with wlroots-eglstreams only changes.

**Comment by Tank-Missile** [comment]
@danvd So what you're saying is, this will require changes to this fork, just KwinFT, and/or something else?

**Comment by danvd** [comment]
@Tank-Missile I think it will require KwinFT changes. Fork does not change wlroots public api, so changes here will be minimal, if ever needed.

If you're interested, here is a link to  KwinFT function for direct gbm usage:
https://gitlab.com/kwinft/kwinft/-/blob/master/render/backend/wlroots/egl_helpers.h#L60

**Comment by subdiff** [comment]
@danvd Do you know what platform should KWinFT ask for additionally? And if this GBM buffer creation would even work with the EGLStreams backend provided here? From what I know Nvidia is working on some integration with GBM but I don't know what's the current state on that. The GBM access is required for creating the dmabuf which we send to wlroots for presenting on an output.

**Comment by PolyMeilex** [comment]
>  but I don't know what's the current state on that.

Recently on GitLab I saw one of the Nvidia devs saying that internally they have sway running (without any forks that is, just GBM), but yeah we don't know when this will see a light of day.

(Kinda off-topic, but I thought I'll throw that in as a fun fact)

**Comment by danvd** [comment]
@subdiff nvidia works with EGL_PLATFORM_DEVICE_EXT

**Comment by frmonteiro** [comment]
> @subdiff nvidia works with EGL_PLATFORM_DEVICE_EXT

Just with adding if It has the extension `EGL_PLATFORM_DEVICE_EXT`?

**Comment by danvd** [comment]
Closing this due to lack of time.

**Comment by subdiff** [comment]
Sorry, I forgot about the ticket here. The next version of KWinFT will have deeper integration with the wlroots renderer and in particular not allocate buffers on its own through GBM. That might make wlroots-eglstreams work directly with KWinFT anyway. Thanks @danvd for your time.

**Comment by danvd** [comment]
Thanks, @subdiff. If there wil be anything except GBM requering this repo changes, please reopen. 
It looks like Nvidia implemented GBM just formally, to say everyone: "Hey, we did it, no more questions, ok?". But in practive their implementation is just a garbage.
