### ISSUE TITLE
Possible NULL dereference at render/egl.c

### ISSUE THREAD

**Issue by git-bruh** [danvd/wlroots-eglstreams#23]
Hi, there is a possible NULL dereference of currentDeviceFile at line 309 of render/egl.c if eglQueryDeviceStringEXT fails. Was trying to figure out why sway kept segfaulting, so i built wlroots with debug symbols, added a null check which allowed it to continue and show an EGL warning that i had wrong perms on /dev/dri/* which helped me fix my issue.�

**Comment by danvd** [comment]
Hi @git-bruh, thank you. Added a check

**Comment by git-bruh** [comment]
Another one here if `drmGetVersion()` fails: https://github.com/danvd/wlroots-eglstreams/blob/b9f5db0e0d4946465a9eb6ecf19f542630ca30ca/backend/drm/drm.c#L1682

**Comment by danvd** [comment]
Thanks, fixed

**Comment by danvd** [comment]
@git-bruh, I'm closing this. Please reopen if something else left.
