### ISSUE TITLE
Incompatible with wayfire due to renaming `wlr_gles2_renderer_get_egl`

### ISSUE THREAD

**Issue by nyanpasu64** [danvd/wlroots-eglstreams#26]
On Arch Linux, I can't build AUR `wayfire-git` against `wlroots-eglstreams-git` because the `wlr_gles2_renderer_get_egl` function is missing. For some reason, wlroots-eglstreams [renames the function](https://github.com/danvd/wlroots-eglstreams/commit/509ee5fdb6f759c1e6f676afd707c7e5d3655c2a#diff-a608d09ac45a14ce9e15d0d1771232a8b2ca3231692c53178bdcd870f6c2c423) to `gles2_renderer_get_egl`. Is this necessary or can it be reverted?

**Comment by danvd** [comment]
Hi @nyanpasu64, sure it can be renamed. Original wlroots added wlr_gles2_renderer_get_egl after gles2_renderer_get_egl was intropduced and seems that git just replaced former after rebasing.

**Comment by nyanpasu64** [comment]
In my local build, I found that renaming the function to `wlr_gles2_renderer_get_egl` more-or-less fixes wayfire so that it mostly works (though XWayland apps show a black screen). So I think it's a good idea to rename the function in your next push.

**Comment by danvd** [comment]
Done
