### ISSUE TITLE
Artifacts when waking from sleep

### ISSUE THREAD

**Issue by sheepymeh** [danvd/wlroots-eglstreams#27]
After waking from sleep, the desktop shows many artifacts:
![20210909_20h18m13s_grim](https://user-images.githubusercontent.com/26665333/132685013-8ac4726d-2696-47e3-ad2a-db86e1ea2c7f.png)
_(screenshot taken with no custom sway config installed)_

Sometimes, the system becomes completely unresponsive:
![signal-2021-09-09-144908_001](https://user-images.githubusercontent.com/26665333/132685125-b77a9be4-9dc9-4932-adcc-13c48d09d60f.jpeg)
TTYs cannot be accessed either from this state.

System info:
OS: Arch Linux
sway/wlroots version: latest from AUR (sway-git and wlrots-eglstreams-git)
GPU: GTX 1070

Thanks for working on this project! sway seems to run very well other than this issue with sleep using your fork of wlroots.

**Comment by PolyMeilex** [comment]
Typical nvidia stuff, I have the same problems on xorg, it is probably related to: https://download.nvidia.com/XFree86/Linux-x86_64/470.63.01/README/powermanagement.html

I have tried solution from the docs many times but I never had any luck, maybe you can try it.

**Comment by sheepymeh** [comment]
It didn't work for me either unfortunately. I am currently using the systemd configuration to sleep but I was already using the ``deep`` mode. Resizing ``/tmp`` didn't help either.

This error happens on every single wake from sleep, usually manifesting as the first form where the machine doesn't lock up completely. It clears up after reloading sway, but the Firefox window becomes completely transparent for some reason, and I have to restart Firefox as well.

**Comment by danvd** [comment]
Corruption can probably may be fixed by forcing full redraw some time after wakeup, but it will work only for sway/wlroots overlays, not for apps, unfortunately. This also is the case for me for a long time and X was suffering from it too, always.

Hanging issue is the most difficult to deal with, however. It blocks in nvidia's eglSwapBuffers implementation. 
And it's known: https://github.com/aritger/eglstreams-kms-example/issues/6#issuecomment-330366392

Previously I wrote and issue on nvidia forums about this, but it was ignored:
https://forums.developer.nvidia.com/t/eglswapbuffers-called-before-eglstreamconsumeracquireattribnv-leads-to-a-deadlock/186758

May be there is workaround does exist, but it's unclear how to find it. I'm trying from time to time. 
Due to this issue I had to disable sleep completely.
Let's keep this open. Maybe sometime the solution will be revealed.

**Comment by sheepymeh** [comment]
I see, hopefully Nvidia fixes this bug sometime in the future.

**Comment by sheepymeh** [comment]
Alright, some progress with the corruption: @PolyMeilex's suggestion did work for me but I didn't follow the instructions properly. It's a pretty common issue and I should've searched online harder beforehand.

If I disable swaylock, the resume function seems to work properly now. I'm not sure why swaylock doesn't work right now.

For future reference or for anyone else who needs it, here are the steps I took for resume to work (Arch):
1. Ensure that `/sys/power/mem_sleep` has `[deep]` in its contents and not `[s2idle]` (mine says `s2idle [deep]`)
2. Create the file `/etc/modprobe.d/nvidia-power-management.conf` and write the line `options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp`
3. Enable the right services with `sudo systemctl enable nvidia-{suspend,hibernate,resume}`
4. Reboot
5. Ensure that `PreserveVideoMemoryAllocations: 1` is in `/proc/driver/nvidia/params`

**Comment by sheepymeh** [comment]
Seems like my config was at fault for the swaylock issue. `swaylock -f` works perfectly fine, and `swaylock -feF` makes it unresponsive.

**Comment by sheepymeh** [comment]
It seems like the hanging issue has worsened in the last update. It used to happen only quite occasionally but now it hangs every time after waking up.

**Comment by sheepymeh** [comment]
Just an update on the hanging after sleep issue: it seems to happen around half the time when I am trying to wake from sleep. I've tried to look at what happens through SSH (the system is still running fine, even the GPU still works for compute tasks).

I must set $SWAYSOCK manually by looking under `/run/user/1000/sway-ipc` as SSH does not have the $SWAYSOCK variable set.

This results in either a dead socket for some old socket that crashed, or there would be a short delay before failing (PID of sway in this case was 7489 so this should be the correct socket):
```
$ export SWAYSOCK=/run/user/1000/sway-ipc.1000.7489.sock
$ swaymsg -t get_tree
00:00:03.099 [common/ipc-client.c:87] Unable to receive IPC response
```

Killing sway with `killall sway` results in a usable system again (of course any open windows are lost), but for some reason I have to issue the command/SIGINT twice. I have attached my [Nvidia bug report](https://github.com/danvd/wlroots-eglstreams/files/7190993/nvidia-bug-report.log.gz) from after the crash in case it helps.

**Comment by danvd** [comment]
@sheepymeh, thanks for details. I've got some thoughts about possible fix. Will check if they make sense.

**Comment by PolyMeilex** [comment]
> I'm trying the NVIDIA 495 beta driver and it seems like this issue might be fixed, at least on first glance. Sway still doesn't work as well on GBM compared to this fork, though.

Oh god, you got me super hyped, can't wait to try it for myself!

**Comment by sheepymeh** [comment]
Nevermind, it seems like I've hit the freezing issue again after updating wlroots. It seems like some commit from @danvd might have been the one that mysteriously fixed the problem, not the drivers, and the code causing the freezing was re-introduced.

**Comment by danvd** [comment]
Closing this. Reopen if issue is still here.
