### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by solarkraft** [danvd/wlroots-eglstreams#3]
I have a whole bunch of questions about this patch, but an issue may not be the right place for them. How about a GitHub discussion (I believe issues can be converted into them)? The IRC channel `#wlroots-eglstreams` on Freenode may also be a good place for talk around this. 

Which compositor did you develop this patch with? Wayfire's wlroots verion is too old to even cherry-pick easily. If it was sway, how did you do it? I'd like to see if this would work for me at all. I still suspect no, since the GPU doesn't output the picture it renders, but hands it off to the internal GPU.

**Comment by danvd** [comment]
I mainly test with sway as it's the only one compositor I'm interested in.
Sway is left untouched, wlroots have nice external api that is left intact too, just lib internals changed a little bit. 
So, just
`sway -V --my-next-gpu-wont-be-nvidia`
and it's working.

BTW, I added discussions page. Lets go there if you don't mind. I'm not too fast to reply, but will try my best.

**Comment by hpfmn** [comment]
Hi Danvd,

I build your library and sway-git on archlinux but it doesn't work. It reports "Failed to open any DRM device"

**Comment by hpfmn** [comment]
Ah it was my fault. I was missing the KMS settings for the propritary driver. Now it works as expected. Sadly qutebrowser won't render anything in wayland mode. And is pixelated when using xcb as QT-Backend (screen scale factor of 2)

**Comment by danvd** [comment]
Closing this due to opened discussions page
