### ISSUE TITLE
Try switching to original wlroots

### ISSUE THREAD

**Issue by danvd** [danvd/wlroots-eglstreams#35]
First things to do:
1. Eliminate flickering
2. Investigate why chromium hangs on start.

**Comment by danvd** [comment]
This is currently does not work at all. Will wait for future driver releases. Maybe they are going to be more stable.

**Comment by PolyMeilex** [comment]
> This is currently does not work at all. Will wait for future driver releases. Maybe they are going to be more stable.

I can confirm that it's the same on my setup, way too unstable in current version.

**Comment by git-bruh** [comment]
@danvd With driver 510.39.01:

wlroots-git (6cdf843a8cef420255e0a55c842530184abb3fe4) - No assertion failures, no memory leaks (nvidia-smi) when using firefox with webrender and resizing. However the original yellow flickering is still present and when using `grim` or `wf-recorder`, says ""

wlroots-eglstreams (f4578db272f998a5009508394b6f38092a09e7ff) - Launches fine, memory leaks as usual with firefox webrender, flickering of window (Wallpaper flashes for a second) when opening new windows.

Also chromium doesn't launch on either of them cuz of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3351

**Comment by git-bruh** [comment]
upon some searching, 875710274 corresponds to the `BGR888` format

**Comment by git-bruh** [comment]
Patched grim with https://termbin.com/gz3r and wf-recorder with https://termbin.com/u7ct (hacky)

Now just have to keep wf-recorder open in the background which makes stuttering pretty rare

**Comment by danvd** [comment]
@git-bruh, thanks for the info!
It's definitely good news. We need to find the root cause of flickering and almost everything will work on vanilla wlroots as it seems.

**Comment by danvd** [comment]
I tried original wlroots today (wit hlatest beta driver). What I want to say is that it's far from being usable for me. Flickering is here even with tinywl which redraws entire screen on each update (so it's does not seem like damage issue). For example, weston does not have this problem.

There is also probably a driver issue: some apps like alacritty are terribly slow. Chrome does not have webgl.

I'm closing this. Let's what when all of this GBM staff will for w/o any modifications.
