### ISSUE TITLE
GPU Memory leaks

### ISSUE THREAD

**Issue by danvd** [danvd/wlroots-eglstreams#41]
client texture streams are deallocated only when client terminates, why? When resizing, old streams are not destroyed.

**Comment by danvd** [comment]
I slightly modified client buffer allocation/destruction. Checked that buffers are destroyed - eglDestroyStream + glDeleteTexture are called for each window size change. 
But still no luck - nvidia-smi shows memory leaks. I'm a bit stuck at the moment. Will search further when time permits.

**Comment by danvd** [comment]
I enabled dma-buf and memory leaks are gone. It's nice that dma-buf works almost fine - all clients now prefer using it instead of eglstream controller :-)

Will close in a week or so if no issues.

**Comment by git-bruh** [comment]
Works fine for me aswell, but chromium has tons of visual glitches (as with vanilla wlroots)

**Comment by danvd** [comment]
I switched to firefox + MOZ_ENABLE_WAYLAND + MOZ_WEBRENDER - it outperforms chrome in almost everything that related to smooth rendering.

**Comment by git-bruh** [comment]
Also, there seems to be the weird clipboard problem that used to happen on original wlroots. If you copy from firefox with ctrl + c and paste it with `wl-paste`, it hangs occasionally.

**Comment by danvd** [comment]
Hmm, I never used wl-paste. Can you share a use case for it?

**Comment by hafeoz** [comment]
> weird clipboard problem that used to happen on original wlroots

Are you referring to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1722369) issue?

**Comment by git-bruh** [comment]
@hafeoz I think so, doesn't seem to happen when just copy pasting from 2 terminals or chromium, only with firefox. The issue was also described [here](https://forums.developer.nvidia.com/t/nvidia-495-on-sway-tutorial-questions-arch-based-distros/192212):

> foot also fails to copy-and-paste text from other applications (warn: selection.c:1602: no data received from clipboard in 2 seconds, aborting)

WAYLAND_DEBUG log: https://termbin.com/hhj6
strace log: https://termbin.com/ji27

Will try the gtk patch suggested in that issue.

**Comment by PolyMeilex** [comment]
I'm pretty sure it's a Firefox thing, as it happens on Gnome as well.

**Comment by danvd** [comment]
I wonder if someone else have the the issues with images/video corruption inside firefox?
![image](https://user-images.githubusercontent.com/5666218/151707562-7915ded5-a987-4b37-8ffa-ab5becb8fede.png)

Seems that other apps aren't affected.

**Comment by danvd** [comment]
Nope, after disabling dmabuf, still the same artifacts :-(. In worst case my gpu has broken, which would be a sad story.

**Comment by danvd** [comment]
Looks like something with my system. AMD gpu has the same artefacts

**Comment by danvd** [comment]
Works well, no visible bugs, no leaks, stable and fast. Looks like Nvidia coped with dmabuf implementation (fingers crossed).
